const backendDomain="https://ecommerce-mauve-alpha.vercel.app/"

const SummaryApi={
    signup:{
        url:`${backendDomain}/api/signup`,
        method:"post"
    },
    signin:{
        url:`${backendDomain}/api/signin`,
        method:"post"
    },
    userDetails:{
        url:`${backendDomain}/api/user-details`,
        method:"get"
    },
    Logout:{
        url:`${backendDomain}/api/userLogout`,
        method:"get"
    },
    allUsers:{
        url:`${backendDomain}/api/all-User`,
        method:"get"
    },
    Updateuser:{
        url:`${backendDomain}/api/update-User`,
        method:"post"
    },
    uploadProduct:{
        url:`${backendDomain}/api/upload-Product`,
        method:"post"
    },
    getProduct:{
        url:`${backendDomain}/api/get-Product`,
        method:"get"
    },
    updateProduct:{
        url:`${backendDomain}/api/update-product`,
        method:"post"
    },
    CategoryProduct:{
        url:`${backendDomain}/api/get-categoryProduct`,
        method:"get"
    },
    CategoryWiseProduct:{
        url:`${backendDomain}/api/category-product`,
        method:"post"
    },
    ProductDetails:{
        url:`${backendDomain}/api/product-details`,
        method:"post"
    },
    addToCart:{
        url:`${backendDomain}/api/addtocart`,
        method:"post"
    },
    countaddtocart:{
        url:`${backendDomain}/api/countaddtocart`,
        method:"get"
    },
    addtoCartProductView:{
        url:`${backendDomain}/api/viewcartproduct`,
        method:"get"
    },
    updateCartProduct:{
        url:`${backendDomain}/api/updatecartproduct`,
        method:"post"
    },
    deleteCartProduct:{
        url:`${backendDomain}/api/deletecartproduct`,
        method:"post"
    },
    searchProduct:{
        url:`${backendDomain}/api/search`,
        method:"get"
    },
    filterProduct:{
        url:`${backendDomain}/api/filter-product`,
        method:"post"
    }
}
export default SummaryApi
